# /etc/uwsgi/sites/backend.ini

[uwsgi]
project = api
base = /backend

uid =  www-data
gid = www-data
chmod-socket = 666
chown-socket = www-data:www-data

chdir = %(base)/%(project)
#home = /backend
wsgi-file = %(base)/%(project)/%(project)/wsgi.py
master = true
processes = 5
threads = 2
socket = %(base)/sockets/uwsgi.sock
logto = %(base)/logs/main.log
harakiri = 60

no-orphans = true
die-on-term = true
memory-report = true
buffer-size = 32768
vacuum = true