version: "2"

services:
  prod_uwsgi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://e10206:rick.007@10.162.64.36:8080
        - https_proxy=http://e10206:rick.007@10.162.64.36:8080
    # network_mode: "bridge"
    # restart: always
    # Set container name
    container_name: prod_uwsgi
    volumes:
      - ./:/backend
    # Change workdir
    working_dir: /backend/api
    # Entablish ports
    ports:
      - "8070:8000"
    # Connect container and host ports
    # stdin_open: true
    # tty: true
    # Run the following command
    command: python manage.py runserver 0.0.0.0:8000
