version: "2"

services:
  core_api_test:
    image: "core_api:latest"
    env_file: .env
    restart: always
    volumes:
      - ../backend:/backend
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - DJANGO_ENV=test
