#upstream django {
#    server unix:///backend/sockets/uwsgi.sock;
#}

server {
    listen 80;

    # The host name to respond to
    server_name ${APP_HOSTNAME};

    charset utf-8;
  
    # max upload size
    client_max_body_size 75M;   # adjust to taste

    location /static/ {
        alias       /backend/static_root/;
    }

    location /media/ {
        alias       /backend/media_root/;
    }

    location / {
        proxy_set_header Upgrade ${DOLLAR}http_upgrade;
        proxy_set_header Connection "upgrade";
        include         /backend/uwsgi/uwsgi_params;
        uwsgi_pass      unix:/backend/sockets/uwsgi.sock;
        #proxy_pass      unix:/backend/sockets/uwsgi.sock;
        #uwsgi_pass      django;
    }


}
