server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
  add_header X-Frame-Options “DENY”;
}
# Cambiar ip por la de producción o testing
add_header Content-Security-Policy "default-src 'self'; form-action 'http://172.31.158.5:8077'; form-action 'http://172.31.158.12:8077';";