version: "2"

services:

  # Add .env
  # nginx_backend:
  #   image: nginx
  #   container_name: nginx_backend
  #   network_mode: "bridge"
  #   restart: always
  #   ports: 
  #     - "8056:80"
  #   depends_on:
  #     - plantilla_backend
  #   # Copy files into container
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/nginx.template
  #     - ../backend:/backend
  #   working_dir: /backend
  #   environment:
  #     - DOLLAR=$$
  #     - plantilla_HOSTNAME=172.31.158.12
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"

  plantilla_backend:
    extends:
      file: base.yml
      service: plantilla_backend
    # If there is no image, build one
    ports: 
      - "8040:8000"
    build:
      args:
        - DJANGO_ENV=prod
    # Set container name
    container_name: identidad_backend
    network_mode: "bridge"
    restart: always
    # Copy backend folder 
    # environment:
    #   - plantilla_HOSTNAME=172.31.158.12
    volumes:
      - ../backend:/backend
    # Change workdir
    working_dir: /backend
    command: gunicorn -c conf/gunicorn_conf.py api.wsgi
  
  # Angular frontend plantilla
  plantilla_frontend:
    image: nginx
    # Name the container
    container_name: identidad_frontend
    # Ports to use
    ports: 
      - "8057:80"
    # Folders and files to copy into the container
    volumes:
      # Copy the plantilla to html folder
      - ../dist/:/usr/share/nginx/html
      # Works only with SPA
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
    # Set environment variables
    stdin_open: true
    tty: true
    depends_on:
      - plantilla_backend