"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from datetime import timedelta
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Add father folder
MAIN_DIR = os.path.dirname(BASE_DIR)


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Party
    'rest_framework',
    'adrf',
    'corsheaders',
    # Own modules
    'authentication.apps.AuthenticationConfig',
    'subscriber_data_collector.apps.SubscriberDataCollectorConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',    # Agregado por la versión nueva de Django
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    # 'DEFAULT_FILTER_BACKENDS':('django_filters.rest_framework.DjangoFilterBackend',
    # ),
     'DEFAULT_RENDERER_CLASSES': (
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
            # 'drf_renderer_xlsx.renderers.XLSXRenderer',
            # 'drf_excel.renderers.XLSXRenderer'                          # Agregado por la versión nueva de Django
        ),
}


PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFYQGeSzijOtbpdDQGYoP7k57hOx\ngNQeYj4CGYO/al/QdYAf38oGaRXhdkacmSxI2iBlUkQixdq35xtZsBDeScnJ0brK\nnJL1Ts4BbeaZDA7AjTmpZ3klvk4y0hErai4lM8+ydsrztHhcu1qY1+SNz4nCIaKX\na/MV4KFpWO/i3izHAgMBAAE=\n-----END PUBLIC KEY-----' # pylint: disable=line-too-long
PRIVATE_KEY = '-----BEGIN RSA PRIVATE KEY-----\nMIICWwIBAAKBgFYQGeSzijOtbpdDQGYoP7k57hOxgNQeYj4CGYO/al/QdYAf38oG\naRXhdkacmSxI2iBlUkQixdq35xtZsBDeScnJ0brKnJL1Ts4BbeaZDA7AjTmpZ3kl\nvk4y0hErai4lM8+ydsrztHhcu1qY1+SNz4nCIaKXa/MV4KFpWO/i3izHAgMBAAEC\ngYBKhsbldVRIS/dopaQu0svb6n5wL1YQWf9ZExhlLm0/a5VUzkVM/SAjAosZuqIp\n5yx8wUDsH/CV5osK9C+za8sZIcQZY2PI+PasXPJ4Q1MlxnxjqDAUeOEMu0RLVE/6\n+5bm1e+zYR/GQBumkOAvQqYloQNGgKZfl1Y/2gqJtlFrgQJBAJYsSly8yhsy8r8h\nlV4A11nJ8gD0vY7n9k0E8S/40apiZPhsy+9KlmSDhrMSf6SXKXw1ba58HNkwDRIb\naLQ8AzsCQQCStiIWRKCqec11HRecI1qBrH/cUv3N4YFFEN3Cl1PpPDkV4vr4x4fl\nu6iuYiefbzDSnwTljw0G91lyHT/e50vlAkEAi01weZAixpI/PW8wuG99VGwREjP0\n9vBTuGRCOybLjwsQ8KUzk7iTw4+CTvB0+T/DmtWQ9c9pj0qUhVxphu84awJAOG9r\naVl43FsCV7ybKmrHE/7BKIWcMChAy8qTI5mGo7+QzgSEOlK2yf6IApyrVT82bq7Q\n+WUvw7A+bhEmUp5yqQJABA36tsYiUa6BR8GnhBaDGNl2q/xyJk8yjwBwcqPumP7T\n6lviopw6ndkLKpnXZr4yjgH3ZjZLfY5hbISovReydw==\n-----END RSA PRIVATE KEY-----' # pylint: disable=line-too-long


# JWT_AUTH = {
#     'JWT_PAYLOAD_HANDLER': 'api.utils.jwt_payload_handler',

#     'JWT_PAYLOAD_GET_USERNAME_HANDLER': 'api.utils.jwt_get_username_from_payload_handler',

#     'JWT_EXPIRATION_DELTA': datetime.timedelta(days=5),

#     'JWT_ALLOW_REFRESH': True,
#     'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(hours=2),

#     'JWT_AUTH_HEADER_PREFIX': 'JWT',

#     'JWT_ENCODE_HANDLER': 'api.utils.jwt_encode_handler',

#     'JWT_DECODE_HANDLER': 'api.utils.jwt_decode_handler',
# }
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=2),
    'ALGORITHM': 'RS256',
    'SIGNING_KEY': PRIVATE_KEY,
    'VERIFYING_KEY': PUBLIC_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    # CORS Headers
    'corsheaders.middleware.CorsMiddleware',
    # Django standard middleware
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (CSS/JS) via ASGI/Uvicorn with correct MIME types
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(MAIN_DIR, "docs/site")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# Root where 'collectstatic' gathers files; WhiteNoise serves from here
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(MAIN_DIR, "docs/site"),
]

# WhiteNoise: serve compressed static files with long-lived cache headers
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'