# Generated by Django 2.0.4 on 2018-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_auth',
            field=models.IntegerField(default=0),
        ),
    ]
