# Generated by Django 2.0.4 on 2018-07-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_failed_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='failed_auth',
            new_name='attempt_fails',
        ),
    ]
