# Generated by Django 2.0.4 on 2018-07-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180702_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='attempt_fails',
            new_name='failed_attempts',
        ),
    ]
