# Generated by Django 2.0.4 on 2018-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180702_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
