# Generated by Django 2.0.4 on 2018-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_previous_failed_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='previous_failed_attempts',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
