# Generated by Django 2.0.4 on 2018-08-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_auto_20180731_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('login_or_logout', models.BooleanField(default=True)),
                ('success_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebAppModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WebApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='webappmodules',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.WebApps'),
        ),
        migrations.AddField(
            model_name='appaudit',
            name='app_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.WebAppModules'),
        ),
        migrations.AddField(
            model_name='appaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessaudit',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.WebApps'),
        ),
        migrations.AddField(
            model_name='accessaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
