# Generated by Django 2.0.4 on 2018-08-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_auto_20180806_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedAccessAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.WebApps')),
            ],
        ),
        migrations.CreateModel(
            name='GrantedAccessAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('login_or_logout', models.BooleanField(default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.WebApps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessaudit',
            name='app',
        ),
        migrations.RemoveField(
            model_name='accessaudit',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessAudit',
        ),
    ]
